version: '3.8'

services:
  nginx:
    image: nginx
    container_name: ${APP_NAME}_nginx
    restart: always
    ports:
      - ${NGINX_PORT}:80
      - ${NGINX_PORT_SSL}:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - nginx_logs:/var/log/nginx
    networks:
      - awesome_network

  content-service:
    build:
      context: ./awesome-content
      dockerfile: Dockerfile
    container_name: ${APP_NAME}_content
    restart: always
    ports:
      - ${CONTENT_SERVICE_PORT}:80
      - ${CONTENT_SERVICE_PORT_SSL}:443
    networks:
      - awesome_network

volumes:
  nginx_logs:
    name: ${APP_NAME}_nginx_logs

networks:
  default:
    name: ${APP_NAME}_network
  awesome_network:
    name: awesome_network
    external: true
